name = "PeriodicOrbits"
uuid = "41be5fce-5647-450b-ae37-a6739b881a1c"
repo = "https://github.com/JuliaDynamics/PeriodicOrbits.jl.git"
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
LeastSquaresOptim = "0fc2ff8b-aaa3-5acd-a817-1944a5e08891"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Combinatorics = "1"
DynamicalSystemsBase = "3.8"
Reexport = "1"
julia = "1.9"
